#!/bin/sh

DATE=`date +%Y-%m-%d`
DIR="/home/reinfurt/backups/radioathenes.tv/"
SQL="$DIR/$DATE.sql"
echo "\n$DATE"
mysqldump -u athenes -pNormanPotter2987 -h 178.128.207.99 radioathenes_tv > $SQL
rsync -azP /var/www/html/media/ $DIR/media

# in process!

#!/bin/sh
# update _local from _remote (db, media/)
# does not work as mysql is not setup to be accessed remotely on n-y-c.org
mysqldump -u nyc_led_full -piusb9d79 -h dev.n-y-c.org n_y_c > /Users/reinfurt/n-y-c.mysql
# mysql -u root -p ica_local < /Users/reinfurt/ica_full.mysql
# rsync -azP reinfurt@ica.art:/var/www/html/media/ /Library/WebServer/Documents/www.ica.local/media
rm /Users/reinfurt/n-y-c.mysql

